project/request/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, SelectField, RadioField
from wtforms.validators import DataRequired
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed
from project.models import User, Role
from project import db, user_datastore


class RequestTicketForm(FlaskForm):
    title = SelectField('Problem', validators=[DataRequired()],
                        choices=[('Computer Software Problem', 'Computer Software Problem'),
                                 ('No Internet Connection', 'No Internet Connection'),
                                 ('Operating System Problem', 'Operating System Problem'),
                                 ('Defective CPU', 'Defective CPU'),
                                 ('Defective Monitor', 'Defective Monitor'),
                                 ('Defective Keyboard', 'Defective Keyboard'),
                                 ('Defective Mouse', 'Defective Mouse'),
                                 ('Others', 'Others')
                                 ])
    description = TextAreaField('Problem Description/Observations', validators=[DataRequired(255)])
    location = StringField('Location', validators=[DataRequired()])
    department = StringField('Department', validators=[DataRequired()])
    local_number = IntegerField('Local Number', validators=[DataRequired('Enter Valid Number')])
    other_contact = StringField('Other Contact Details', validators=[DataRequired()])
    file = FileField('Optional Attachment', validators=[FileAllowed(['docx', 'pdf', 'jpg'])])
    submit = SubmitField('Submit Request')


class RecommendationForm(FlaskForm):
    recommendation = TextAreaField('Recommendation(For Repair,For Replacement,Others)', validators=[
                                   DataRequired('Please type A Recommendation')])
    submit = SubmitField('Submit Recommendation')

project/common/views.py
from flask_security import login_required, current_user, roles_accepted
from flask import Blueprint, request, url_for, render_template, flash, redirect, abort
from project import db, user_datastore
from wtforms import SubmitField, SelectField, StringField, FileField
from flask_wtf import FlaskForm
from wtforms import ValidationError
from sqlalchemy import desc
from flask_security import utils
from project.common.forms import RoleForm,UpdatePassword
from project.common.picture_handler import add_profile_pic
from project.models import User, RequestTicket, Departments
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired, Email, EqualTo, Length

common = Blueprint('common', __name__)


@common.route("/edit/profile", methods=['GET', 'POST'])
@login_required
def profile():
    class UpdateUserForm(FlaskForm):
        email = StringField('Email', validators=[DataRequired(), Email()])
        firstname = StringField('First Name', validators=[DataRequired()])
        lastname = StringField('First Name', validators=[DataRequired()])
        picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
        submit = SubmitField('Update')

        def check_email(self, field):
            if User.query.filter_by(email=field.data).first():
                raise ValidationError('Your email has been registered already!')

    form = UpdateUserForm()

    if form.validate_on_submit():
        if form.picture.data:
            email = current_user.email
            pic = add_profile_pic(form.picture.data, email)
            current_user.profile_image = pic

        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('common.profile'))

    elif request.method == 'GET':
        form.firstname.data = current_user.firstname
        form.lastname.data = current_user.lastname
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('/common/profile.html', profile_image=profile_image, form=form)


@common.route("/user/profile/<email>", methods=['GET', 'POST'])
@login_required
def user_page(email):
    form = RoleForm()
    account = User.query.filter_by(email=email).first_or_404()
    return render_template('/common/user_page.html', account=account, form=form)


@common.route("/user/reports")
def user_tickets():
    if current_user.has_role('admin') or current_user.has_role('super-admin') or current_user.has_role('tech-support'):
        abort(403)
    tickets = db.session.query(RequestTicket, User)\
        .outerjoin(User, RequestTicket.owner_id == User.id)\
        .order_by(desc(RequestTicket.date_requested))\
        .filter(RequestTicket.owner_id == current_user.id)\

    return render_template('/common/user_tickets.html', tickets=tickets)

@common.route("/user/update_password", methods=['GET','POST'])
def update_password():
    form = UpdatePassword()
    if form.validate_on_submit():
        current_user.password = utils.encrypt_password(form.password.data)
        db.session.commit()
        flash('You updated your passsword')
    return render_template('/common/update_password.html',form=form)

project/request/views.py
import os
from flask import Blueprint, request, url_for, render_template, flash, redirect, send_from_directory, current_app, abort
from flask_security import login_required, current_user, roles_accepted
from project import db, user_datastore, app
from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField
from sqlalchemy import desc
from project.request.action import for_action
from wtforms.validators import DataRequired
from project.request.assign import auto_technician
from project.request.tracking_code_generator import generate_code
from project.request.forms import RequestTicketForm, RecommendationForm
from project.request.file_handler import save_file, new_file_name
from project.models import RequestTicket, User, Feedback, Role


requests = Blueprint('requests', __name__)

################################################################################


@requests.route('/uploads/<path:filename>')
def file_download(filename):
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename=filename)

################################################################################


@requests.route('/request/<ownerid>/<ticketno>/', methods=['GET', 'POST'])
@login_required
def tickets_view(ownerid, ticketno):
    tech = db.session.query(User).filter(User.roles.any(Role.name == 'tech-support')).all()
    request = RequestTicket.query.filter_by(id=ticketno, owner_id=ownerid).first_or_404()
    list = []
    for user in tech:
        if 'tech-support' in user.roles:
            choice = (user.email, f"{user.firstname} {user.lastname}")
            list.append(choice)

    class AssignForm(FlaskForm):
        technician = SelectField('Technician', validators=[DataRequired()], choices=list)
        submit = SubmitField('Assign')

    class ActionForm(FlaskForm):
        action = for_action(request.title)
        if action == 'repair_only':
            choice = [('Repaired', 'Repaired'),
                     ]
        else:
            choice = [('Repaired', 'Repaired'),
                     ('Replaced', 'Replaced'),
                     ]

        action = SelectField('Action Taken', validators=[DataRequired('Please type the Action Taken')],
                             choices=choice)
        submit = SubmitField('Submit Action')

    form = AssignForm()
    rec_form = RecommendationForm()
    act_form = ActionForm()
    owner = user_datastore.get_user(ownerid)
    recommended_user = user_datastore.get_user(request.recommended_by)
    assign_user = user_datastore.get_user(request.assigned_to)
    feedback = Feedback.query.filter_by(ticket_id=ticketno).first()

    if request.status == 'Pending' and current_user.email == request.assigned_to:
        request.status = 'On-Going'
        db.session.commit()

    if rec_form.validate_on_submit():
        request.recommendation = rec_form.recommendation.data
        request.recommended_by = current_user.email
        db.session.commit()
        flash("You added recomendation to the problem")
        return redirect(url_for('requests.tickets_view', ownerid=request.owner_id, ticketno=request.id))

    if act_form.validate_on_submit():
        request.action_taken = act_form.action.data
        request.status = act_form.action.data
        db.session.commit()
        flash("You added the actions taken")
        return redirect(url_for('requests.tickets_view', ownerid=request.owner_id, ticketno=request.id))

    if form.validate_on_submit():
        if form.technician.data:
            request.status = 'Pending'
            request.assigned_to = form.technician.data
            user = user_datastore.get_user(form.technician.data)
            request.assigned_name = f"{user.firstname} {user.lastname}"
            db.session.commit()
            flash("Successfully assigned a technician")
            return redirect(url_for('requests.tickets_view', ownerid=request.owner_id, ticketno=request.id))

    if current_user.has_role('super-admin') or current_user.has_role('admin') or current_user.has_role('tech-support') or owner.id == current_user.id:
        return render_template('/request/view_request.html',
                               request=request,
                               owner=owner,
                               form=form,
                               rec_form=rec_form,
                               act_form=act_form,
                               recommended_user=recommended_user,
                               assign_user=assign_user,
                               feedback=feedback
                               )
    else:
        abort(403)

################################################################################


@requests.route('/request', methods=['GET', 'POST'])
@login_required
def request_ticket():
    if current_user.has_role('tech-support') or current_user.has_role('admin'):
        flash('You can not create a ticket')
        return redirect(url_for('index'))
    else:
        pass
    form = RequestTicketForm()
    myfile = None
    if form.validate_on_submit():
        if form.file.data:
            number = db.session.query(User).join(User.requests).filter(
                RequestTicket.owner_id == current_user.id).count()

            myfile = save_file(form.file.data, new_file_name(current_user.email, number))
        technician = auto_technician()  # from assign py
        # get technician name
        name = User.query.filter_by(email=technician).first()
        tech_name = f"{name.firstname} {name.lastname}"
        code = generate_code()
        NewTicket = RequestTicket(owner_id=current_user.id,
                                  title=form.title.data,
                                  description=form.description.data,
                                  department=form.department.data,
                                  local_number=form.local_number.data,
                                  location=form.location.data,
                                  other_contact=form.other_contact.data,
                                  date_requested=datetime.utcnow(),
                                  file_attached=myfile,
                                  status='Pending',
                                  assigned_to=technician,
                                  assigned_name=tech_name,
                                  track_code=code
                                  )
        db.session.add(NewTicket)
        db.session.commit()
        flash('Request Submitted')
        return redirect(url_for('requests.code',code=code))

    return render_template('/request/request.html', form=form)

################################################################################


@requests.route('/request/pending')
@roles_accepted('admin', 'super-admin')
def pending_tickets():
    tickets = db.session.query(RequestTicket, User)\
        .outerjoin(User, RequestTicket.owner_id == User.id)\
        .order_by(desc(RequestTicket.date_requested))\
        .filter(RequestTicket.status == 'Pending')
    return render_template('/request/requests_pending.html', tickets=tickets)

################################################################################


@requests.route('/request/all')
@roles_accepted('admin', 'super-admin', 'tech-support')
def all_tickets():
    tickets = db.session.query(RequestTicket, User)\
        .outerjoin(User, RequestTicket.owner_id == User.id)\
        .order_by(desc(RequestTicket.date_requested))
    #name = db.session.query(User).filter_by(User.email==tickets)
    return render_template('/request/requests_all.html', tickets=tickets)

################################################################################


@requests.route("/request/assigned")
@login_required
def assigned_tickets():
    tickets = db.session.query(RequestTicket, User)\
        .outerjoin(User, RequestTicket.owner_id == User.id)\
        .filter(RequestTicket.assigned_to == current_user.email)

    return render_template('/request/requests_assigned.html', tickets=tickets)

################################################################################


@requests.route("/request/feedback/<requestid>/<ownerid>/<technician>", methods=['POST'])
def feedback(ticketid, ownerid, technician):
    user = User.query.filter_by(id=ownerid).first_or_404()
    if user.id == current_user.id:
        pass
    else:
        abort(404)
    textfb = request.form['text-feedback']
    rate = request.form['rating']
    feed = Feedback(ticket_id=ticketid,
                    technician=technician,
                    rating=rate,
                    feedback=textfb
                    )
    db.session.add(feed)
    db.session.commit()
    flash("Thanks for submitting your feedback")
    return redirect(url_for('requests.tickets_view', requestid=requestid, ownerid=ownerid))


################################################################################


@requests.route("/request/code/<code>")
@login_required
def code(code):
    request = db.session.query(RequestTicket).filter(RequestTicket.track_code==code).first_or_404()
    code = request.track_code
    return render_template('/request/code.html',code=code)

project/templates/request/code.html
{% extends "base.html" %}
{% block title %}New Complain{% endblock %}
{% block content %}
<div class="container">
  <br>
  <div align="center">
    <h1>Your Tracking Code is {{code}}</h1>
  </div>
</div>
<br>
{% endblock %}

project/templates/request/request.html
{% extends "base.html" %}
{% block title %}New Complain{% endblock %}
{% block content %}
<div class="container">
  <div align="center">
    <h1>Create New Request</h1>
  </div>
  <br>
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-lg-8">
      <form method="POST" action = "" enctype="multipart/form-data">
        {% from "includes/_macros.html" import render_field %}
        {{ form.hidden_tag() }}
        <div class="row">
          <div class="col-lg">
            <div class="form-group">
              {{ render_field(form.title,class='form-control') }}
            </div>
            <div class="form-group">
              {{ render_field(form.description,class='form-control') }}
            </div>
            <div class="form-group">
              {{ render_field(form.location,class='form-control') }}
            </div>
            <div class="form-group">
              {{ render_field(form.department,class='form-control') }}
            </div>
          </div>
          <div class="col-lg">
            <div class="form-group">
              {{ render_field(form.local_number,class='form-control') }}
            </div>
            <div class="form-group">
              {{ render_field(form.other_contact,class='form-control') }}
            </div>
            <div class="form-group">
              {{ render_field(form.file,class='form-control') }}
            </div>
            <br>
            {{form.submit(class='btn btn-primary')}}
          </div>
        </div>

      </form>
    </div>
    <div class="col-sm">
    </div>
  </div>
</div>
<br>
{% endblock %}

project/templates/request/requests_all.html
{% extends "base.html" %}
{% block links %}
<link rel="stylesheet" type="text/css" href="/static/datatable/datatables.css">
<script src="/static/datatable/datatables.js"></script>
{% endblock %}
{% block title %}All Reports{% endblock %}
{% block content %}

<div class="container">
  <script>
  $(document).ready( function () {
  $('#open').DataTable({
    "aaSorting": []
  }
  );
  } );
  </script>
  <table id="open" class="display">
    <thead>
      <tr>
        <th>Date Submitted</th>
        <th>Status</th>
        <th>Track Code</th>
        <th>Owner of ticket</th>
        <th>Assigned to</th>
        <th>Problem</th>
        <th>Department</th>
        <th>More Info</th>
      </tr>
    </thead>
    <h3 align="center">All Reports</h3>
    <tbody>
      {% for ticket,user in tickets %}
      <tr>
        <td>{{ticket.date_requested.strftime('%B %d, %Y, %I:%M %p')}}</td>
        <td>{{ticket.status}}</td>
        <td>{{ticket.track_code}}</td>
        <td><a href="{{url_for('common.user_page',email=user.email)}}" target="_blank">{{user.firstname}} {{user.lastname}}</a></td>
        <td>{% if ticket.assigned_to %}
          <a href="{{url_for('common.user_page',email=ticket.assigned_to)}}" target="_blank">{{ticket.assigned_name}}</a>
          {% else %}None{% endif %}
          </td>
        <td>{{ticket.title}}</td>
        <td>{{ticket.department}}</td>
        <td><a href="{{url_for('requests.tickets_view',ownerid=ticket.owner_id,ticketno=ticket.id)}}">Details</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<br>
{% endblock %}

project/templates/request/requests_assigned.html
{% extends "base.html" %}
{% block links %}
<link rel="stylesheet" type="text/css" href="/static/datatable/datatables.css">
<script src="/static/datatable/datatables.js"></script>
{% endblock %}
{% block title %}Request Assigned to {{current_user.firstname}} {{current_user.lastname}}{% endblock %}
{% block content %}

<div class="container">
  <script>
  $(document).ready( function () {
  $('#open').DataTable({
    "aaSorting": []
  }
  );
  } );
  </script>
  <table id="open" class="display">
    <thead>
      <tr>
        <th>Date Submitted</th>
        <th>Status</th>
        <th>Track Code</th>
        <th>Owner of ticket</th>
        <th>Problem</th>
        <th>Department</th>
        <th>More Info</th>
      </tr>
    </thead>
    <h3 align="center">Request Assigned to {{current_user.firstname}} {{current_user.lastname}}</h3>
    <tbody>
      {% for ticket,user in tickets %}
      <tr>
        <td>{{ticket.date_requested.strftime('%B %d, %Y, %I:%M %p')}}</td>
        <td>{{ticket.status}}</td>
        <th>{{ticket.track_code}}</th>
        <td><a href="{{url_for('common.user_page',email=user.email)}}" target="_blank">{{user.firstname}} {{user.lastname}}</a></td>
        <td>{{ticket.title}}</td>
        <td>{{ticket.department}}</td>
        <td><a href="{{url_for('requests.tickets_view',ownerid=ticket.owner_id,ticketno=ticket.id,status='on-going')}}">Details</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<br>
{% endblock %}

project/templates/request/requests_pending.html
{% extends "base.html" %}
{% block links %}
<link rel="stylesheet" type="text/css" href="/static/datatable/datatables.css">
<script src="/static/datatable/datatables.js"></script>
{% endblock %}
{% block title %}Pending Reports{% endblock %}
{% block content %}

<div class="container">
  <script>
  $(document).ready( function () {
  $('#open').DataTable({
    "aaSorting": []
  }
  );
  } );
  </script>
  <table id="open" class="display">
    <thead>
      <tr>
        <th>Date Submitted</th>
        <th>Status</th>
        <th>Track Code</th>
        <th>Owner of ticket</th>
        <th>Assigned to</th>
        <th>Problem</th>
        <th>Department</th>
        <th>More Info</th>
      </tr>
    </thead>
    <h3 align="center">Pending Reports</h3>
    <tbody>
      {% for ticket,user in tickets %}
      <tr>
        <td>{{ticket.date_requested.strftime('%B %d, %Y, %I:%M %p')}}</td>
        <td>{{ticket.status}}</td>
        <td>{{ticket.track_code}}</td>
        <td><a href="{{url_for('common.user_page',email=user.email)}}" target="_blank">{{user.firstname}} {{user.lastname}}</a></td>
        <td>{% if ticket.assigned_to %}
          <a href="{{url_for('common.user_page',email=ticket.assigned_to)}}" target="_blank">{{ticket.assigned_name}}</a>
          {% else %}None{% endif %}</td>
        <td>{{ticket.title}}</td>
        <td>{{ticket.department}}</td>
        <td><a href="{{url_for('requests.tickets_view',ownerid=ticket.owner_id,ticketno=ticket.id)}}">Details</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<br>
{% endblock %}

project/templates/request/view_request.html
{% extends "base.html" %}
{% block links %}
<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/static/css/star.css">
{% endblock %}
{% block title %}View request {{request.id}}{% endblock %}
{% block content %}
<div class="container">
	<div class="jumbotron bg-white">
		{% if feedback != None %}
		{% if feedback.rating != None %}
		{% set number = feedback.rating | int %}
		<div align="center">
			<p>Rating: {% for each in range(number) %}
				<i class="active fa fa-star" aria-hidden="true" style="color:#FCD116;">
				</i>{% endfor %}</p>
		{% endif %}
			<p>Feedback: {{feedback.feedback}}</p>
		</div>
		<br>
		{% endif %}
  <div class="row">
    <div class="col-sm">
						<p><span class="h6">Problem: </span>{{request.title}}</p>
						<p><span class="h6">Problem Description/Observations: </span>{{request.description}}</p>
						<p><span class="h6">Status: </span>{{request.status}}</p>
						<p><span class="h6">Owner Name: </span><a href="{{url_for('common.user_page',email=owner.email)}}">{{owner.firstname}} {{owner.lastname}}</a></p>
						<p><span class="h6">Date Submitted: </span>{{request.date_requested.strftime('%B %d, %Y')}}</p>
						<p><span class="h6">Attached File: {% if request.file_attached %}
						</span><a href="{{url_for('requests.file_download',filename=request.file_attached)}}" download>{{request.file_attached}}</a>
							{% else %}
							 No file
							{% endif %}
						</p>
						{% if request.recommendation %}
						<p><span class="h6">Recommendation: </span>{{request.recommendation}}</p>
						{% endif %}
						{% if request.recommended_by %}
						<p><span class="h6">Recommended by: </span>
							<a href="{{url_for('common.user_page',email=request.recommended_by)}}" target="_blank">{{recommended_user.firstname}} {{recommended_user.lastname}}</a></p>
						{% endif %}
		</div>
    <div class="col-sm">
			<p><span class="h6">Department: </span>{{request.department}}</p>
			<p><span class="h6">Local Number: </span>{{request.local_number}}</p>
			<p><span class="h6">Location: </span>{{request.location}}</p>
			<p><span class="h6">Other Contact: </span>{{request.other_contact}}</p>
			<p><span class="h6">Assigned to: </span>{% if request.assigned_to != None %}
				<a href="{{url_for('common.user_page',email=request.assigned_to)}}" target="_blank">{{assign_user.firstname}} {{assign_user.lastname}}</a>
				{% else %}None{% endif %}</p>
				{% if request.action_taken %}
				<p><span class="h6">Action Taken: </span>{{request.action_taken}}</p>
				{% endif %}
		</div>
		<div class="col-sm">
					{% from "includes/_macros.html" import render_field %}
					{% if current_user.has_role('tech-support') and request.action_taken != None and request.recomendation == None %}
					<form method="POST" action="">
						{{rec_form.hidden_tag()}}
						<div class="form-group">
							{{ render_field(rec_form.recommendation,class='form-control') }}
						</div>
						{{rec_form.submit(class='btn btn-primary')}}
					</form>
					<br>
					{% elif current_user.has_role('tech-support') and request.action_taken == None %}
					<form method="POST" action="">
						{% from "includes/_macros.html" import render_field %}
						{{rec_form.hidden_tag()}}
						<div class="form-group">
							{{ render_field(act_form.action,class='form-control') }}
						</div>
						{{act_form.submit(class='btn btn-primary')}}
					</form>
					<br>
					{% endif %}
					{% if current_user.has_role('admin') or current_user.has_role('super-admin') %}
					<div>
						<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Re-Assign</button>
					</div>
					<br>
					{% endif %}
					{% if request.owner_id == current_user.id and feedback == None and request.assigned_to != None and request.action_taken %}
					<form action="{{url_for('requests.feedback',requestid=request.id,ownerid=request.owner_id,technician=request.assigned_to)}}" method="POST">
						<div align="center">
							<div class="star-rating">
										<input id="star-5" type="radio" name="rating" value="5">
										<label for="star-5" title="5 stars">
												<i class="active fa fa-star" aria-hidden="true"></i>
										</label>
										<input id="star-4" type="radio" name="rating" value="4">
										<label for="star-4" title="4 stars">
												<i class="active fa fa-star" aria-hidden="true"></i>
										</label>
										<input id="star-3" type="radio" name="rating" value="3">
										<label for="star-3" title="3 stars">
												<i class="active fa fa-star" aria-hidden="true"></i>
										</label>
										<input id="star-2" type="radio" name="rating" value="2">
										<label for="star-2" title="2 stars">
												<i class="active fa fa-star" aria-hidden="true"></i>
										</label>
										<input id="star-1" type="radio" name="rating" value="1">
										<label for="star-1" title="1 star">
												<i class="active fa fa-star" aria-hidden="true"></i>
										</label>
										<p><small>Rate the technician</small></p>
									</div>
						</div>
								<textarea name="text-feedback" class="form-control" id="text-feedback" placeholder="Write your feedback here..." required></textarea>
								<br>
								<input class="btn btn-customdarkviolet" type="submit" value="Submit Feedback and Rating" >
					</form>
					{% endif %}
		</div>
		</div>
    </div>
</div>
<br>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Assign request</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" method="POST">
      <div class="modal-body">
        {{ form.hidden_tag() }}
        {{form.technician.label}} {{ form.technician(class="form-control") }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        {{form.submit(class="btn btn-primary")}}
      </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}